apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-cert
spec:
  commonName: {{ .Values.ingress.host }}
  secretName: {{ .Chart.Name }}-cert-secret
  dnsNames:
    - {{ .Values.ingress.host }}
  issuerRef:
    name: {{ .Values.global.certIssuer.name }}
    kind: ClusterIssuer
