apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-app
    spec:
      containers:
      - name: {{ .Chart.Name }}-image
        image: {{ .Values.image }}:{{ .Values.imageTag | default "latest" }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        volumeMounts:
        - name: config-volume
          mountPath: "/src/nitter.conf"
          subPath: "nitter.conf"
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Chart.Name }}-configmap
