apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-ingress-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ .Chart.Name }}-service
          port: {{ .Values.port }}

  tls:
    secretName: {{ .Chart.Name }}-cert-secret
