apiVersion: v2
name: homecloud
description: A Helm chart to manage and encapsulate several applications under one HomeCloud umbrella
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: nitter
    version: "0.1.0"
  - name: traefik
    version: "9.18.1"
    repository: "https://helm.traefik.io/traefik"
