apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}-image
            image: {{ .Values.image }}:{{ .Values.imageTag | default "latest" }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - echo url="https://www.duckdns.org/update?domains={{ .Values.secret.domain }}&token={{ .Values.secret.token }}&ip=" | curl -k -o /dnslog/duck.log -K -;
              if [ "$(cat '/dnslog/duck.log')" == "OK" ]; then touch /dnslog/healthy; else rm -rf /dnslog/healthy; fi
            volumeMounts:
              - name: dnslog
                mountPath: /dnslog
            livenessProbe:
              exec:
                command:
                  - cat
                  - /dnslog/healthy
              initialDelaySeconds: 300
              periodSeconds: 300
          volumes:
            - name: dnslog
              hostPath:
                path: "{{ .Values.mountPoint }}/logs"
          restartPolicy: OnFailure
