apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Chart.Name }}-app
